#!/usr/local/rvm/rubies/ruby-1.9.3-p194/bin/ruby

require "/home/fermani/workspace/rubox/config/environment"

output = 0
begin
  
  $stdout.reopen("./log/out.txt", "a")
  $stderr.reopen("./log/err.txt", "a")

  puts "-------------------------------------------------\n"
  puts "[" + Time.new.to_s + "]\n"
  #autor del commit
  gitLog = `git log --pretty=' Autor: [%an] %n Commit: %H %n Mensaje: %s' -n 1`
  #lo escribo en el log
  puts gitLog.to_s
  #obtengo el login. Formato: [<login>] <name>
  login = gitLog[/\[(.*)\]/][1]
  #Obtengo el usuario de la base de datos
  user = User.where("login='" + login + "'").first

  path = Dir.pwd
  pName = File.basename(path,".git")
  project = Project.where("name = '" + pName.to_s + "'").first

  if (user == nil || project == nil)
    puts "Error de validacion de usuario y proyecto"
    output = 1
  else 
    pers = Permission.where("user_id = " + user.id.to_s + " and project_id = " + project.id.to_s).first
    if (pers == nil || pers.type.description == "read") 
      puts "Error. El usuario no tiene permisos"
      output = 1
    else 
      puts "Cambios aceptados"
    end
  end

rescue Exception => e
  output = 1
  #some error occur, dir not writable etc.
ensure
#  file.close unless file == nil
end


exit(output)
